spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service?useSSL=false&allowPublicKeyRetrieval=true
    username: auth_service
    password: auth_service
  liquibase:
    change-log: classpath:db/liquibase-changeLog.xml